### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ComteDeBussy** [twirl/The-API-Book#10]
В [главе 11, пункт 9](https://github.com/twirl/The-API-Book/blob/gh-pages/src/ru/clean-copy/02-Раздел%20I.%20Проектирование%20API/05.md#клиент-всегда-должен-знать-полное-состояние-системы), скорее всего, неправильный падеж в первом же предложении:

> Правило можно ещё сформулировать так: не заставляйте клиент гадать.

Полагаю, слово «клиент» планировалось написать в родительном падеже: «клиента».

**Comment by twirl** [comment]
Нет, здесь клиент = клиентское устройство, неодушевлённое.
