### ISSUE TITLE
Расхождение ru и en

### ISSUE THREAD

**Issue by angryermine** [twirl/The-API-Book#15]
>   * либо в запросе содержатся только идентификаторы, и имплементации методов сами обратятся за нужными данными через какие-то внутренние API.

есть предложение по этой строке, по аналогии с англоязычным вариантом

> or the request contains only data identifiers, and next in chain handler will request pieces of data it needs via some internal APIs.

кажется, более корректным было бы так:
  * либо в запросе содержатся только идентификаторы и следующие обработчики в цепочке сами обратятся за нужными данными через какие-то внутренние API.

**Comment by twirl** [comment]
Хм. Ну для меня это одно и то же — имплементации методов они и есть следующие обработчики в цепочке.

**Comment by angryermine** [comment]
Я раза три перечитал эту строку и полез в en за уточнением

**Comment by twirl** [comment]
оооок, подумаю )

**Comment by twirl** [comment]
@angryermine see https://github.com/twirl/The-API-Book/commit/913ba8d2e8caaf3a63e1d496cf8f903de261d1b2

**Comment by angryermine** [comment]
Спасибо :)
