### ISSUE TITLE
Несогласованность числа между местоимением и существительным

### ISSUE THREAD

**Issue by Cliffart44** [twirl/The-API-Book#30]
В самом конце:
> ...каким своим срезом она выступает во взаимодействии с _каким объектами_.
https://github.com/twirl/The-API-Book/blob/27c244deb4f1dc40b8f313169c18eb77a549ed69/src/ru/clean-copy/03-%D0%A0%D0%B0%D0%B7%D0%B4%D0%B5%D0%BB%20II.%20%D0%9E%D0%B1%D1%80%D0%B0%D1%82%D0%BD%D0%B0%D1%8F%20%D1%81%D0%BE%D0%B2%D0%BC%D0%B5%D1%81%D1%82%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D1%8C/06.md?plain=1#L13

**Comment by twirl** [comment]
Пофиксил, спасибо
