### ISSUE TITLE
Вопрос про POST и /search

### ISSUE THREAD

**Issue by chuprik** [twirl/The-API-Book#33]
Привет! Спасибо за труд :)

У меня возник вопрос на который я не нашел ответа в книжке. Почему для endpoint /search используется POST, а не GET? С одной стороны интересны причины и точка зрения, а с другой стороны, как мне кажется, в книгу было бы круто добавить это объяснение, так как POST это про создание данных на сервере, а GET про чтение (но с другой стороны есть идемпотентность и история поиска).

**Comment by twirl** [comment]
Согласно букве стандарта, GET возвращает некоторое представление ресурса. `search` — ресурс-поисковик, его представление нам не очень интересно — нам интересны результаты его (поисковика) работы, т.е. то, как этот ресурс обработал посланный нами запрос. А это, опять же согласно букве RFC, как раз определение метода POST.

Если подходить к вопросу чисто практически, то вопрос ставится так: уведомить клиент о чём мы считаем более важным — о том, что метод безопасный (GET) или некэшируемый (POST)? Дальше начинается некоторая вкусовщина, но с моей личной точки зрения POST семантически корректнее.

Подробнее по этим вопросам я пройдусь в планируемом разделе про HTTP.
