### ISSUE TITLE
Опечатка в главе про сильную связность

### ISSUE THREAD

**Issue by kuzkok** [twirl/The-API-Book#41]
Опечатка в 

>Вопрос этот с подвохом: в том виде, как мы описали партнёрск**Ы**й API 

https://github.com/twirl/The-API-Book/blob/f272af58db591578f3bbea88496e46d1f532ef70/src/ru/clean-copy/03-%D0%A0%D0%B0%D0%B7%D0%B4%D0%B5%D0%BB%20II.%20%D0%9E%D0%B1%D1%80%D0%B0%D1%82%D0%BD%D0%B0%D1%8F%20%D1%81%D0%BE%D0%B2%D0%BC%D0%B5%D1%81%D1%82%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D1%8C/04.md?plain=1#L3

**Comment by twirl** [comment]
Исправил, спасибо. Соберу новые версии чуть позже.
