### ISSUE TITLE
Описание функции и примеры её использования не совпадают

### ISSUE THREAD

**Issue by kuzkok** [twirl/The-API-Book#42]
volume.format vs formatVolume в комментарии ниже.

https://github.com/twirl/The-API-Book/blob/a4978440410e6edda5110238263f2e04810ae43d/src/ru/clean-copy/03-%D0%A0%D0%B0%D0%B7%D0%B4%D0%B5%D0%BB%20II.%20%D0%9E%D0%B1%D1%80%D0%B0%D1%82%D0%BD%D0%B0%D1%8F%20%D1%81%D0%BE%D0%B2%D0%BC%D0%B5%D1%81%D1%82%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D1%8C/04.md?plain=1#L62

**Comment by twirl** [comment]
Это так и задумано ;)
l10n.volume.format — клиентская функция в SDK. Чтобы она заработала с кастомными локалями, необходимо задать их через серверное API.
По-видимому, следует выразить эту мысль более явно. Спасибо, подумаю над этим.

**Comment by twirl** [comment]
Addressed in 44b0b8e
