### ISSUE TITLE
Опечатка в коде app.display(coffeeMachines);

### ISSUE THREAD

**Issue by ivankoshcheev** [twirl/The-API-Book#43]
https://github.com/twirl/The-API-Book/blob/69097c27d844ae6c5ec642cecc7095c3f96651cc/src/ru/clean-copy/02-%D0%A0%D0%B0%D0%B7%D0%B4%D0%B5%D0%BB%20I.%20%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%20API/04.md

В псевдокоде, вероятно, должно быть `app.display(matchingCoffeeMachines);` вместо `app.display(coffeeMachines);`

**Comment by twirl** [comment]
Исправил, спасибо!
