### ISSUE TITLE
Возможно, опечатка, но требуется уточнение

### ISSUE THREAD

**Issue by angryermine** [twirl/The-API-Book#49]
[Тут](https://github.com/twirl/The-API-Book/blob/gh-pages/src/ru/clean-copy/05-%5BВ%20разработке%5D%20Раздел%20IV.%20HTTP%20API%20и%20REST/06.md?plain=1#L135
) слово "нетразитивным" кажется должно быть "нетранзитивным"

**Comment by twirl** [comment]
Действительно, должно, спасибо! И ведь проверка орфографии, собака, ничего не подчеркнула.
Пофиксил в 0070e6368bee79a8f337bfb4fe8bd17bafba5540
